// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateSnippet(arg1) {
  return window['go']['main']['App']['CreateSnippet'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function ExportJSON() {
  return window['go']['main']['App']['ExportJSON']();
}

export function GetActiveCollection() {
  return window['go']['main']['App']['GetActiveCollection']();
}

export function GetCloseToTrayEnabled() {
  return window['go']['main']['App']['GetCloseToTrayEnabled']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetSnippets() {
  return window['go']['main']['App']['GetSnippets']();
}

export function GetStartAtLoginEnabled() {
  return window['go']['main']['App']['GetStartAtLoginEnabled']();
}

export function GetStartAtLoginSupported() {
  return window['go']['main']['App']['GetStartAtLoginSupported']();
}

export function GetTraySnippetLimit() {
  return window['go']['main']['App']['GetTraySnippetLimit']();
}

export function ImportJSON() {
  return window['go']['main']['App']['ImportJSON']();
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function SelectCollection(arg1) {
  return window['go']['main']['App']['SelectCollection'](arg1);
}

export function SetCloseToTrayEnabled(arg1) {
  return window['go']['main']['App']['SetCloseToTrayEnabled'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetStartAtLoginEnabled(arg1) {
  return window['go']['main']['App']['SetStartAtLoginEnabled'](arg1);
}

export function SetTraySnippetLimit(arg1) {
  return window['go']['main']['App']['SetTraySnippetLimit'](arg1);
}

export function UpdateSnippet(arg1) {
  return window['go']['main']['App']['UpdateSnippet'](arg1);
}
