// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateSnippet(arg1:domain.CreateSnippetInput):Promise<domain.Snippet>;

export function CreateCollection(arg1:string):Promise<domain.Collection>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function GetCloseToTrayEnabled():Promise<boolean>;

export function GetLanguage():Promise<string>;

export function GetActiveCollection():Promise<domain.Collection>;

export function GetCollections():Promise<Array<domain.Collection>>;

export function GetSnippets():Promise<Array<domain.Snippet>>;

export function GetStartAtLoginEnabled():Promise<boolean>;

export function GetStartAtLoginSupported():Promise<boolean>;

export function GetTraySnippetLimit():Promise<number>;

export function SetCloseToTrayEnabled(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SelectCollection(arg1:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function SetStartAtLoginEnabled(arg1:boolean):Promise<void>;

export function SetTraySnippetLimit(arg1:number):Promise<void>;

export function UpdateSnippet(arg1:domain.Snippet):Promise<domain.Snippet>;
