// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSnippet(arg1) {
  return window['go']['main']['App']['CreateSnippet'](arg1);
}

export function CreateSnippetsFile() {
  return window['go']['main']['App']['CreateSnippetsFile']();
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function GetCloseToTrayEnabled() {
  return window['go']['main']['App']['GetCloseToTrayEnabled']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetSnippets() {
  return window['go']['main']['App']['GetSnippets']();
}

export function GetSnippetsStoragePath() {
  return window['go']['main']['App']['GetSnippetsStoragePath']();
}

export function GetStartAtLoginEnabled() {
  return window['go']['main']['App']['GetStartAtLoginEnabled']();
}

export function GetStartAtLoginSupported() {
  return window['go']['main']['App']['GetStartAtLoginSupported']();
}

export function GetTraySnippetLimit() {
  return window['go']['main']['App']['GetTraySnippetLimit']();
}

export function PickExistingSnippetsFile() {
  return window['go']['main']['App']['PickExistingSnippetsFile']();
}

export function SetCloseToTrayEnabled(arg1) {
  return window['go']['main']['App']['SetCloseToTrayEnabled'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetSnippetsStoragePath(arg1) {
  return window['go']['main']['App']['SetSnippetsStoragePath'](arg1);
}

export function SetStartAtLoginEnabled(arg1) {
  return window['go']['main']['App']['SetStartAtLoginEnabled'](arg1);
}

export function SetTraySnippetLimit(arg1) {
  return window['go']['main']['App']['SetTraySnippetLimit'](arg1);
}

export function UpdateSnippet(arg1) {
  return window['go']['main']['App']['UpdateSnippet'](arg1);
}
